=== AdamCoops/api-documentation-frontend/test/resources/raml/V2/business-rates/2.0/endpoints/my-organisation/messages/schemas/get-message-summary-response-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Messages Summary",
  "type": "object",
  "additionalProperties": false,
  "definitions": {},
  "properties": {
    "_links": {
      "type": "object",
      "additionalProperties": false,
      "description": "HATEOAS links",
      "properties": {
        "self": {
          "type": "object",
          "additionalProperties": false,
          "description": "Links to this resource",
          "properties": {
            "href": {
              "type": "string",
              "format": "uri",
              "pattern": "^https?://\\w+",
              "description": "URL for this link"
            },
            "template": {
              "type": "boolean",
              "description": "Is the HREF a RFC-6570 compliant URI Template"
            }
          },
          "required": [
            "href",
            "template"
          ]
        },
        "first": {
          "type": "object",
          "additionalProperties": false,
          "description": "Links to the first page of results for this resource",
          "properties": {
            "href": {
              "type": "string",
              "format": "uri",
              "pattern": "^https?://\\w+",
              "description": "URL for this link"
            },
            "template": {
              "type": "boolean",
              "description": "Is the HREF a RFC-6570 compliant URI Template"
            }
          },
          "required": [
            "href",
            "template"
          ]
        },
        "previous": {
          "type": "object",
          "additionalProperties": false,
          "description": "Links to the previous page of results for this resource",
          "properties": {
            "href": {
              "type": "string",
              "format": "uri",
              "pattern": "^https?://\\w+",
              "description": "URL for this link"
            },
            "template": {
              "type": "boolean",
              "description": "Is the HREF a RFC-6570 compliant URI Template"
            }
          },
          "required": [
            "href",
            "template"
          ]
        },
        "next": {
          "type": "object",
          "additionalProperties": false,
          "description": "Links to the next page of results for this resource",
          "properties": {
            "href": {
              "type": "string",
              "format": "uri",
              "pattern": "^https?://\\w+",
              "description": "URL for this link"
            },
            "template": {
              "type": "boolean",
              "description": "Is the HREF a RFC-6570 compliant URI Template"
            }
          },
          "required": [
            "href",
            "template"
          ]
        },
        "last": {
          "type": "object",
          "additionalProperties": false,
          "description": "Links to the last page of results for this resource",
          "properties": {
            "href": {
              "type": "string",
              "format": "uri",
              "pattern": "^https?://\\w+",
              "description": "URL for this link"
            },
            "template": {
              "type": "boolean",
              "description": "Is the HREF a RFC-6570 compliant URI Template"
            }
          },
          "required": [
            "href",
            "template"
          ]
        }
      },
      "required": [
        "self",
        "first"
      ]
    },
    "page": {
      "type": "integer",
      "description": "The page number"
    },
    "pageSize": {
      "type": "integer",
      "description": "The page size",
      "minimum": 10,
      "maximum": 100
    },
    "total": {
      "type": "integer",
      "description": "The total number of elements"
    },
    "messages": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "_links": {
            "type": "object",
            "additionalProperties": false,
            "description": "HATEOAS links",
            "properties": {
              "detailed": {
                "type": "object",
                "additionalProperties": false,
                "description": "Links to the detailed message",
                "properties": {
                  "href": {
                    "type": "string",
                    "format": "uri",
                    "pattern": "^https?://\\w+",
                    "description": "URL for this link"
                  },
                  "template": {
                    "type": "boolean",
                    "description": "Is the HREF a RFC-6570 compliant URI Template"
                  }
                },
                "required": [
                  "href",
                  "template"
                ]
              }
            }
          },
          "messageId": {
            "type": "integer"
          },
          "subject": {
            "type": "string"
          },
          "recipientOrganisationName": {
            "type": "string"
          },
          "ipOrganisationName": {
            "type": "string"
          },
          "agentOrganisationName": {
            "type": "string"
          },
          "caseRef": {
            "type": "string"
          },
          "submissionId": {
            "type": "string"
          },
          "createdDateTime": {
            "type": "string"
          },
          "address": {
            "type": "string"
          },
          "effectiveDateTime": {
            "type": "string"
          },
          "lastReadAt": {
            "type": "string"
          }
        },
        "required": [
          "_links",
          "messageId",
          "subject",
          "recipientOrganisationName",
          "ipOrganisationName",
          "submissionId",
          "createdDateTime",
          "address",
          "effectiveDateTime"
        ]
      }
    }
  },
  "required": [
    "_links",
    "page",
    "pageSize",
    "total",
    "messages"
  ]
}

=== AdamCoops/api-documentation-frontend/test/resources/raml/V2/business-rates/2.0/endpoints/my-organisation/messages/examples/get-message-summary-response-example.json
{
  "_links" : {
    "self" : {
      "href" : "http://api.service.hmrc.gov.uk/my-organisation/messages?page=1&pageSize=15&sortDirection=ASC",
      "template" : false
    },
    "first" : {
      "href" : "http://api.service.hmrc.gov.uk/my-organisation/messages?page=1&pageSize=15&sortDirection=ASC",
      "template" : false
    },
    "last" : {
      "href" : "http://api.service.hmrc.gov.uk/my-organisation/messages?page=1&pageSize=15&sortDirection=ASC",
      "template" : false
    }
  },
  "page" : 1,
  "pageSize" : 15,
  "total" : 1,
  "messages" : [ {
    "_links" : {
      "detailed": {
        "href": "http://api.service.hmrc.gov.uk/my-organisation/messages/1",
        "template": false
      }
    },
    "messageId" : 1,
    "subject" : "Check Acknowledgement",
    "recipientOrganisationName" : "Acme",
    "ipOrganisationName" : "Acme",
    "submissionId" : "PLZ60Y",
    "createdDateTime" : "2018-11-16T12:08:05.213Z",
    "address" : "47, Test",
    "effectiveDateTime" : "2018-11-16T12:08:05.213Z"
  } ]
}
