=== AdamCoops/api-documentation-frontend/test/resources/raml/V2/business-rates/2.0/endpoints/property-search/schemas/property-search-response-schema.json
{
  "$id": "http://api.service.hmrc.gov.uk/example.json",
  "type": "object",
  "additionalProperties": false,
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "_links": {
      "type": "object",
      "additionalProperties": false,
      "description": "HATEOAS links",
      "properties": {
        "self": {
          "type": "object",
          "additionalProperties": false,
          "description": "Links to this endpoint",
          "properties": {
            "href": {
              "type": "string",
              "format": "uri",
              "pattern": "^https?://\\w+",
              "description": "URL for this link"
            },
            "template": {
              "type": "boolean",
              "description": "Is the HREF a RFC-6570 compliant URI Template"
            }
          },
          "required": [
            "href",
            "template"
          ]
        },
        "first": {
          "type": "object",
          "additionalProperties": false,
          "description": "Links to the first page of results for this resource",
          "properties": {
            "href": {
              "type": "string",
              "format": "uri",
              "pattern": "^https?://\\w+",
              "description": "URL for this link"
            },
            "template": {
              "type": "boolean",
              "description": "Is the HREF a RFC-6570 compliant URI Template"
            }
          },
          "required": [
            "href",
            "template"
          ]
        },
        "next": {
          "type": "object",
          "additionalProperties": false,
          "description": "Links to the next page of results for this resource",
          "properties": {
            "href": {
              "type": "string",
              "format": "uri",
              "pattern": "^https?://\\w+",
              "description": "URL for this link"
            },
            "template": {
              "type": "boolean",
              "description": "Is the HREF a RFC-6570 compliant URI Template"
            }
          },
          "required": [
            "href",
            "template"
          ]
        }
      },
      "required": [
        "self",
        "first"
      ]
    },
    "pageSize": {
      "type": "integer",
      "description": "The page size",
      "minimum": 10,
      "maximum": 100
    },
    "total": {
      "type": "integer",
      "description": "The total number of properties matching your query criteria"
    },
    "properties": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "description": "An array of properties matching the search criteria",
        "properties": {
          "_links": {
            "type": "object",
            "additionalProperties": false,
            "description": "HATEOAS links",
            "properties": {
              "valuations": {
                "type": "object",
                "additionalProperties": false,
                "description": "Link to the valuations for this property",
                "properties": {
                  "href": {
                    "type": "string",
                    "format": "uri",
                    "pattern": "^https?://\\w+",
                    "description": "URL for this link"
                  },
                  "template": {
                    "type": "boolean",
                    "description": "Is the HREF a RFC-6570 compliant URI Template"
                  }
                },
                "required": [
                  "href",
                  "template"
                ]
              },
              "currentValuation": {
                "type": "object",
                "additionalProperties": false,
                "description": "Link to the current valuation for this property",
                "properties": {
                  "href": {
                    "type": "string",
                    "format": "uri",
                    "pattern": "^https?://\\w+",
                    "description": "URL for this link"
                  },
                  "template": {
                    "type": "boolean",
                    "description": "Is the HREF a RFC-6570 compliant URI Template"
                  }
                },
                "required": [
                  "href",
                  "template"
                ]
              }
            }
          },
          "uarn": {
            "type": "integer",
            "description": "Unique Address Reference Number (UARN)"
          },
          "billingAuthorityReference": {
            "type": "string",
            "description": "The reference number for the local billing authority"
          },
          "address": {
            "type": "string",
            "description": "The full, combined address of the property"
          },
          "description": {
            "type": "string",
            "description": "The description of the property type (e.g. office)"
          },
          "specialCategoryCode": {
            "type": "string",
            "description": "Special category code"
          }
        },
        "required": [
          "_links",
          "uarn",
          "billingAuthorityReference",
          "address"
        ]
      }
    }
  },
  "required": [
    "_links",
    "pageSize",
    "total",
    "properties"
  ]
}

=== AdamCoops/api-documentation-frontend/test/resources/raml/V2/business-rates/2.0/endpoints/property-search/examples/property-search-response-example.json
{
  "_links": {
    "self": {
      "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/property-search?pageSize=15&afterAddress=15,%20THIRD%20AVENUE,%20HOVE,%20EAST%20SUSSEX,%20BN3%202PB&afterUarn=110400141&postcode=BN3",
      "template": false
    },
    "first": {
      "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/property-search?pageSize=15&postcode=BN3",
      "template": false
    },
    "next": {
      "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/property-search?pageSize=15&afterAddress=RALLI%20HALL,%20DENMARK%20VILLAS,%20HOVE,%20EAST%20SUSSEX,%20BN3%203TH&afterUarn=87569141&postcode=BN3",
      "template": false
    }
  },
  "total": 12,
  "pageSize": 15,
  "properties": [
    {
      "_links": {
        "valuations": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/335891141/valuations",
          "template": false
        },
        "currentValuation": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/335891141/valuations/10362602?projection=summary",
          "template": false
        }
      },
      "uarn": 335891141,
      "billingAuthorityReference": "170050600200",
      "address": "16 -20, SHIRLEY STREET, HOVE, EAST SUSSEX, BN3 3WJ",
      "description": "CLUB HOUSE AND PREMISES",
      "specialCategoryCode": "060G"
    },
    {
      "_links": {
        "valuations": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/103765141/valuations",
          "template": false
        },
        "currentValuation": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/103765141/valuations/10362590?projection=summary",
          "template": false
        }
      },
      "uarn": 103765141,
      "billingAuthorityReference": "160044400860",
      "address": "86, PORTLAND ROAD, HOVE, EAST SUSSEX, BN3 5DL",
      "description": "CLUB HOUSE AND PREMISES",
      "specialCategoryCode": "060G"
    },
    {
      "_links": {
        "valuations": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/241341141/valuations",
          "template": false
        },
        "currentValuation": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/241341141/valuations/10362632?projection=summary",
          "template": false
        }
      },
      "uarn": 241341141,
      "billingAuthorityReference": "170056300210",
      "address": "BOWLS PAVILION, THE BEACH, WESTERN ESPLANADE, HOVE, EAST SUSSEX, BN3 4GP",
      "description": "CLUB HOUSE AND PREMISES",
      "specialCategoryCode": "060G"
    },
    {
      "_links": {
        "valuations": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/88422000/valuations",
          "template": false
        },
        "currentValuation": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/88422000/valuations/10362587?projection=summary",
          "template": false
        }
      },
      "uarn": 88422000,
      "billingAuthorityReference": "040410",
      "address": "BRIGHTON & HOVE CRICKET CLUB NEVILL RECREATION GROUND, NEVILL ROAD, HOVE, EAST SUSSEX, BN3 7BT",
      "description": "CLUB HOUSE AND PREMISES",
      "specialCategoryCode": "060G"
    },
    {
      "_links": {
        "valuations": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/10078091000/valuations",
          "template": false
        },
        "currentValuation": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/10078091000/valuations/10362554?projection=summary",
          "template": false
        }
      },
      "uarn": 10078091000,
      "billingAuthorityReference": "044332",
      "address": "CLUBHOUSE & STORE, BRUNSWICK LAWNS, KINGS ESPLANADE, HOVE, EAST SUSSEX, BN3 2WN",
      "description": "CLUB HOUSE AND PREMISES",
      "specialCategoryCode": "060G"
    },
    {
      "_links": {
        "valuations": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/10505631000/valuations",
          "template": false
        },
        "currentValuation": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/10505631000/valuations/10362626?projection=summary",
          "template": false
        }
      },
      "uarn": 10505631000,
      "billingAuthorityReference": "061176",
      "address": "EAST BOWLS PAVILION, THE BEACH, WESTERN ESPLANADE, HOVE, EAST SUSSEX, BN3 4GP",
      "description": "CLUB HOUSE AND PREMISES",
      "specialCategoryCode": "060G"
    },
    {
      "_links": {
        "valuations": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/116255000/valuations",
          "template": false
        },
        "currentValuation": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/116255000/valuations/10362566?projection=summary",
          "template": false
        }
      },
      "uarn": 116255000,
      "billingAuthorityReference": "040483",
      "address": "HOVE LAGOON WATERSPORTS CENTRE, HOVE LAGOON, KINGSWAY, HOVE, EAST SUSSEX, BN3 4LX",
      "description": "CLUB HOUSE AND PREMISES",
      "specialCategoryCode": "060G"
    },
    {
      "_links": {
        "valuations": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/241342141/valuations",
          "template": false
        },
        "currentValuation": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/241342141/valuations/10362629?projection=summary",
          "template": false
        }
      },
      "uarn": 241342141,
      "billingAuthorityReference": "170056300050",
      "address": "PT BOWLS PAVILION, THE BEACH, WESTERN ESPLANADE, HOVE, EAST SUSSEX, BN3 4GP",
      "description": "CLUB HOUSE AND PREMISES",
      "specialCategoryCode": "060G"
    },
    {
      "_links": {
        "valuations": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/236159141/valuations",
          "template": false
        },
        "currentValuation": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/236159141/valuations/10362539?projection=summary",
          "template": false
        }
      },
      "uarn": 236159141,
      "billingAuthorityReference": "130021400100",
      "address": "R/O 10, GLEBE VILLAS, HOVE, EAST SUSSEX, BN3 5SN",
      "description": "CLUB HOUSE AND PREMISES",
      "specialCategoryCode": "060G"
    },
    {
      "_links": {
        "valuations": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/236423141/valuations",
          "template": false
        },
        "currentValuation": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/236423141/valuations/10362542?projection=summary",
          "template": false
        }
      },
      "uarn": 236423141,
      "billingAuthorityReference": "130024501560",
      "address": "R/O 156, HANGLETON ROAD, HOVE, EAST SUSSEX, BN3 7SH",
      "description": "CLUB HOUSE AND PREMISES",
      "specialCategoryCode": "060G"
    },
    {
      "_links": {
        "valuations": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/87569141/valuations",
          "template": false
        },
        "currentValuation": {
          "href": "http://api.service.hmrc.gov.uk/organisations/business-rates/properties/87569141/valuations/10362530?projection=summary",
          "template": false
        }
      },
      "uarn": 87569141,
      "billingAuthorityReference": "120014100810",
      "address": "RALLI HALL, DENMARK VILLAS, HOVE, EAST SUSSEX, BN3 3TH",
      "description": "CLUB HOUSE AND PREMISES",
      "specialCategoryCode": "060G"
    }
  ]
}
