=== AdamCoops/api-documentation-frontend/test/resources/raml/V2/business-rates/2.0/endpoints/my-organisation/clients/property-links/schemas/my-clients-property-links-response-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "My Clients Property Links",
  "type": "object",
  "additionalProperties": false,
  "definitions": {},
  "properties": {
    "_links": {
      "type": "object",
      "additionalProperties": false,
      "description": "HATEOAS links",
      "properties": {
        "self": {
          "type": "object",
          "additionalProperties": false,
          "description": "Links to this resource",
          "properties": {
            "href": {
              "type": "string",
              "format": "uri",
              "pattern": "^https?://\\w+",
              "description": "URL for this link"
            },
            "template": {
              "type": "boolean",
              "description": "Is the HREF a RFC-6570 compliant URI Template"
            }
          },
          "required": [
            "href",
            "template"
          ]
        },
        "first": {
          "type": "object",
          "additionalProperties": false,
          "description": "Links to the first page of results for this resource",
          "properties": {
            "href": {
              "type": "string",
              "format": "uri",
              "pattern": "^https?://\\w+",
              "description": "URL for this link"
            },
            "template": {
              "type": "boolean",
              "description": "Is the HREF a RFC-6570 compliant URI Template"
            }
          },
          "required": [
            "href",
            "template"
          ]
        },
        "previous": {
          "type": "object",
          "additionalProperties": false,
          "description": "Links to the previous page of results for this resource",
          "properties": {
            "href": {
              "type": "string",
              "format": "uri",
              "pattern": "^https?://\\w+",
              "description": "URL for this link"
            },
            "template": {
              "type": "boolean",
              "description": "Is the HREF a RFC-6570 compliant URI Template"
            }
          },
          "required": [
            "href",
            "template"
          ]
        },
        "next": {
          "type": "object",
          "additionalProperties": false,
          "description": "Links to the next page of results for this resource",
          "properties": {
            "href": {
              "type": "string",
              "format": "uri",
              "pattern": "^https?://\\w+",
              "description": "URL for this link"
            },
            "template": {
              "type": "boolean",
              "description": "Is the HREF a RFC-6570 compliant URI Template"
            }
          },
          "required": [
            "href",
            "template"
          ]
        },
        "last": {
          "type": "object",
          "additionalProperties": false,
          "description": "Links to the last page of results for this resource",
          "properties": {
            "href": {
              "type": "string",
              "format": "uri",
              "pattern": "^https?://\\w+",
              "description": "URL for this link"
            },
            "template": {
              "type": "boolean",
              "description": "Is the HREF a RFC-6570 compliant URI Template"
            }
          },
          "required": [
            "href",
            "template"
          ]
        }
      },
      "required": [
        "self",
        "first"
      ]
    },
    "page": {
      "type": "integer",
      "description": "The page number"
    },
    "pageSize": {
      "type": "integer",
      "description": "The page size",
      "minimum": 10,
      "maximum": 100
    },
    "total": {
      "type": "integer",
      "description": "The total number of elements"
    },
    "propertyLinks": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "_links": {
            "type": "object",
            "additionalProperties": false,
            "description": "HATEOAS links",
            "properties": {
              "self": {
                "type": "object",
                "additionalProperties": false,
                "description": "Link to this resource",
                "properties": {
                  "href": {
                    "type": "string",
                    "format": "uri",
                    "pattern": "^https?://\\w+",
                    "description": "URL for this link"
                  },
                  "template": {
                    "type": "boolean",
                    "description": "Is the HREF a RFC-6570 compliant URI Template"
                  }
                },
                "required": [
                  "href",
                  "template"
                ]
              }
            }
          },
          "id": {
            "type": "integer",
            "description": "Unique ID for this property link"
          },
          "submissionId": {
            "type": "string",
            "description": "Unique submission ID for this property link"
          },
          "status": {
            "type": "string",
            "description": "Status of this property link",
            "enum": [
              "APPROVED",
              "PENDING",
              "DECLINED",
              "REVOKED",
              "MORE_EVIDENCE_REQUIRED"
            ]
          },
          "createdDateTime": {
            "type": "string",
            "format": "date-time",
            "description": "The date and time (ISO Date Time String) of when the property link was created"
          },
          "startDate": {
            "type": "string",
            "format": "date",
            "description": "The date from which the property link is active"
          },
          "endDate": {
            "type": "string",
            "format": "date",
            "description": "The date until which the property link is active"
          },
          "uarn": {
            "type": "integer",
            "description": "The UARN (Unique Address Reference Number) of the linked property"
          },
          "address": {
            "type": "string",
            "description": "The address of the linked property"
          },
          "localAuthorityRef": {
            "type": "string",
            "description": "The local authority reference number for the linked property"
          },
          "appointedDate": {
            "type": "string",
            "format": "date",
            "description": "The date on which the agent was appointed to the property link"
          },
          "client": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "organisationId": {
                "type": "integer",
                "description": "Unique ID for the client organisation"
              },
              "organisationName": {
                "type": "string",
                "description": "The name of the client organisation"
              }
            },
            "required": [
              "organisationId",
              "organisationName"
            ]
          }
        },
        "required": [
          "_links",
          "id",
          "submissionId",
          "status",
          "createdDateTime",
          "startDate",
          "uarn",
          "address",
          "localAuthorityRef",
          "appointedDate",
          "client"
        ]
      }
    }
  },
  "required": [
    "_links",
    "page",
    "pageSize",
    "total",
    "propertyLinks"
  ]
}

=== AdamCoops/api-documentation-frontend/test/resources/raml/V2/business-rates/2.0/endpoints/my-organisation/clients/property-links/examples/my-clients-property-links-response-example.json
{
  "_links": {
    "self": {
      "href": "http://api.service.hmrc.gov.uk/my-organisation/clients/all/property-links?page=1&pageSize=10",
      "template": false
    },
    "first": {
      "href": "http://api.service.hmrc.gov.uk/my-organisation/clients/all/property-links?page=1&pageSize=10",
      "template": false
    },
    "next": {
      "href": "http://api.service.hmrc.gov.uk/my-organisation/clients/all/property-links?page=2&pageSize=10",
      "template": false
    },
    "last": {
      "href": "http://api.service.hmrc.gov.uk/my-organisation/clients/all/property-links?page=2&pageSize=10",
      "template": false
    }
  },
  "page": 1,
  "pageSize": 10,
  "total": 11,
  "propertyLinks": [
    {
      "_links": {
        "self": {
          "href": "http://api.service.hmrc.gov.uk/my-organisation/clients/all/property-links/PL1ZR7QBN1?projection=detailed",
          "template": false
        }
      },
      "id": 10000000000001,
      "submissionId": "PL1ZR7QBN1",
      "status": "APPROVED",
      "createdDateTime": "2017-10-01T10:10:10Z",
      "startDate": "2019-01-22",
      "uarn": 8735379000,
      "address": "BLOCK J UNIT 215 TOWER BRIDGE BUSINESS COMPLEX, CLEMENTS ROAD, LONDON, SE16 4DG",
      "localAuthorityRef": "1940002152213J",
      "appointedDate": "2019-01-22",
      "client": {
        "organisationId": 123,
        "organisationName": "Client Organisation Name"
      }
    },
    {
      "_links": {
        "self": {
          "href": "http://api.service.hmrc.gov.uk/my-organisation/clients/all/property-links/PL1ZR7QBN2?projection=detailed",
          "template": false
        }
      },
      "id": 10000000000002,
      "submissionId": "PL1ZR7QBN2",
      "status": "PENDING",
      "createdDateTime": "2017-10-01T10:10:10Z",
      "startDate": "2019-01-22",
      "uarn": 212542239,
      "address": "2ND FLR 42B, WORCESTER ROAD, BROMSGROVE, WORCS, B61 7AE",
      "localAuthorityRef": "1101911000148",
      "appointedDate": "2019-01-22",
      "client": {
        "organisationId": 123,
        "organisationName": "Client Organisation Name"
      }
    },
    {
      "_links": {
        "self": {
          "href": "http://api.service.hmrc.gov.uk/my-organisation/clients/all/property-links/PL1ZR7QBN3?projection=detailed",
          "template": false
        }
      },
      "id": 10000000000003,
      "submissionId": "PL1ZR7QBN3",
      "status": "DECLINED",
      "createdDateTime": "2017-10-01T10:10:10Z",
      "startDate": "2019-01-22",
      "uarn": 212542239,
      "address": "132, ALDSWORTH AVENUE, GORING-BY-SEA, WORTHING, WEST SUSSEX, BN12 4UU",
      "localAuthorityRef": "1101911000148",
      "appointedDate": "2019-01-22",
      "client": {
        "organisationId": 123,
        "organisationName": "Client Organisation Name"
      }
    },
    {
      "_links": {
        "self": {
          "href": "http://api.service.hmrc.gov.uk/my-organisation/clients/all/property-links/PL1ZR7QBN4?projection=detailed",
          "template": false
        }
      },
      "id": 10000000000004,
      "submissionId": "PL1ZR7QBN4",
      "status": "REVOKED",
      "createdDateTime": "2017-10-01T10:10:10Z",
      "startDate": "2019-01-22",
      "uarn": 212542239,
      "address": "117, MONTAGUE STREET, WORTHING, WEST SUSSEX, BN11 3BP",
      "localAuthorityRef": "1101911000148",
      "appointedDate": "2019-01-22",
      "client": {
        "organisationId": 123,
        "organisationName": "Client Organisation Name"
      }
    },
    {
      "_links": {
        "self": {
          "href": "http://api.service.hmrc.gov.uk/my-organisation/clients/all/property-links/PL1ZR7QBN5?projection=detailed",
          "template": false
        }
      },
      "id": 10000000000005,
      "submissionId": "PL1ZR7QBN5",
      "status": "DECLINED",
      "createdDateTime": "2017-10-01T10:10:10Z",
      "startDate": "2019-01-22",
      "uarn": 212544239,
      "address": "1, BISHOP CROFT, HIGH STREET, HENFIELD, WEST SUSSEX, BN5 9DA",
      "localAuthorityRef": "1101911000148",
      "appointedDate": "2019-01-22",
      "client": {
        "organisationId": 123,
        "organisationName": "Client Organisation Name"
      }
    },
    {
      "_links": {
        "self": {
          "href": "http://api.service.hmrc.gov.uk/my-organisation/clients/all/property-links/PL1ZR7QBN6?projection=detailed",
          "template": false
        }
      },
      "id": 10000000000006,
      "submissionId": "PL1ZR7QBN6",
      "status": "REVOKED",
      "createdDateTime": "2017-10-01T10:10:10Z",
      "startDate": "2019-01-22",
      "uarn": 212342239,
      "address": "142, ALDSWORTH AVENUE, GORING-BY-SEA, WORTHING, WEST SUSSEX, BN12 4UU",
      "localAuthorityRef": "1101911000148",
      "appointedDate": "2019-01-22",
      "client": {
        "organisationId": 123,
        "organisationName": "Client Organisation Name"
      }
    },
    {
      "_links": {
        "self": {
          "href": "http://api.service.hmrc.gov.uk/my-organisation/clients/all/property-links/PL1ZR7QBN7?projection=detailed",
          "template": false
        }
      },
      "id": 10000000000007,
      "submissionId": "PL1ZR7QBN7",
      "status": "DECLINED",
      "createdDateTime": "2017-10-01T10:10:10Z",
      "startDate": "2019-01-22",
      "uarn": 9217709000,
      "address": "BREWERS FAYRE AND PREMIER INN, FITZROY ROAD, EXETER, EX1 3LJ",
      "localAuthorityRef": "1101911000148",
      "appointedDate": "2019-01-22",
      "client": {
        "organisationId": 123,
        "organisationName": "Client Organisation Name"
      }
    },
    {
      "_links": {
        "self": {
          "href": "http://api.service.hmrc.gov.uk/my-organisation/clients/all/property-links/PL1ZR7QBN8?projection=detailed",
          "template": false
        }
      },
      "id": 10000000000008,
      "submissionId": "PL1ZR7QBN8",
      "status": "REVOKED",
      "createdDateTime": "2017-10-01T10:10:10Z",
      "startDate": "2019-01-22",
      "uarn": 1022036000,
      "address": "DRIVING TEST CENTRE, ASHLAND STREET, WOLVERHAMPTON, WV3 0BN",
      "localAuthorityRef": "1101911000148",
      "appointedDate": "2019-01-22",
      "client": {
        "organisationId": 123,
        "organisationName": "Client Organisation Name"
      }
    },
    {
      "_links": {
        "self": {
          "href": "http://api.service.hmrc.gov.uk/my-organisation/clients/all/property-links/PL1ZR7QBN9?projection=detailed",
          "template": false
        }
      },
      "id": 10000000000009,
      "submissionId": "PL1ZR7QBN9",
      "status": "DECLINED",
      "createdDateTime": "2017-10-01T10:10:10Z",
      "startDate": "2019-01-22",
      "uarn": 1022036000,
      "address": "DRIVING TEST CENTRE, ASHLAND STREET, WOLVERHAMPTON, WV3 0BN",
      "localAuthorityRef": "1101911000148",
      "appointedDate": "2019-01-22",
      "client": {
        "organisationId": 123,
        "organisationName": "Client Organisation Name"
      }
    },
    {
      "_links": {
        "self": {
          "href": "http://api.service.hmrc.gov.uk/my-organisation/clients/all/property-links/PL1ZR7QBN10?projection=detailed",
          "template": false
        }
      },
      "id": 10000000000010,
      "submissionId": "PL1ZR7QBN10",
      "status": "REVOKED",
      "createdDateTime": "2017-10-01T10:10:10Z",
      "startDate": "2019-01-22",
      "uarn": 3974063000,
      "address": "GEORGES MEETING HOUSE 38, SOUTH STREET, EXETER, EX1 1ED",
      "localAuthorityRef": "1101911000148",
      "appointedDate": "2019-01-22",
      "client": {
        "organisationId": 123,
        "organisationName": "Client Organisation Name"
      }
    },
    {
      "_links": {
        "self": {
          "href": "http://api.service.hmrc.gov.uk/my-organisation/clients/all/property-links/PL1ZR7QBN11?projection=detailed",
          "template": false
        }
      },
      "id": 10000000000011,
      "submissionId": "PL1ZR7QBN11",
      "status": "REVOKED",
      "createdDateTime": "2017-10-01T10:10:10Z",
      "startDate": "2019-01-22",
      "uarn": 3974063001,
      "address": "GEORGES MEETING HOUSE 39, SOUTH STREET, EXETER, EX1 1ED",
      "localAuthorityRef": "1101911000148",
      "appointedDate": "2019-01-22",
      "client": {
        "organisationId": 123,
        "organisationName": "Client Organisation Name"
      }
    }
  ]
}
