=== AdamCoops/api-documentation-frontend/test/resources/services/api-documentation-test-service/conf/1.2/schemas/user-update-request.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "User update",
  "type": "object",
  "properties": {
    "id": {
      "description": "The user ID",
      "type": "string",
      "example": "550e8400-e29b-41d4-a716-446655440000"
    },
    "name": {
      "description": "The user name",
      "type": "string",
      "example": "user name"
    },
    "displayName": {
      "description": "The display name",
      "type": "string",
      "example": "display name"
    },
    "email": {
      "description": "The email address",
      "type": "string",
      "example": "user@example.com"
    },
    "profile": {
      "description": "The user's profile",
      "type": "object",
      "properties": {
        "active": {
          "description": "Whether the user is active or not",
          "type": "boolean",
          "example": "true"
        },
        "failedLoginAttempts": {
          "description": "How many times the user has failed to login",
          "type": "number",
          "example": "3"
        },
        "permissions": {
          "description": "Whether the user is active or not",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "preferences": {
          "description": "The user's preferences",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "description": "The preference name",
                "type": "string",
                "example": "COLOUR"
              },
              "value": {
                "description": "The preference value",
                "type": "string",
                "example": "RED"
              }
            },
            "required": ["name", "value"]
          }
        }
      },
      "required": ["active", "failedLoginAttempts", "permissions"]
    }
  },
  "required": ["id", "name", "email", "profile"]
}

=== AdamCoops/api-documentation-frontend/test/resources/services/api-documentation-test-service/conf/1.1/examples/user-update.json
{
  "id": "550e8400-e29b-41d4-a716-446655440000",
  "name": "user name",
  "displayName": "display name",
  "email": "user@example.com",
  "profile": {
    "active": true,
    "failedLoginAttempts": 3,
    "permissions": ["POST", "MODERATOR"],
    "preferences": [
      {
        "name": "COLOUR",
        "value": "RED"
      },
      {
        "name": "ORIENTATION",
        "value": "LANDSCAPE"
      }
    ]
  }
}
