=== AdamCoops/api-documentation-frontend/test/resources/raml/V2/business-rates/2.0/endpoints/my-organisation/clients/schemas/get-my-clients-response-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "My Clients",
  "type": "object",
  "additionalProperties": false,
  "definitions": {},
  "properties": {
    "_links": {
      "type": "object",
      "additionalProperties": false,
      "description": "HATEOAS links",
      "properties": {
        "self": {
          "type": "object",
          "additionalProperties": false,
          "description": "Links to this resource",
          "properties": {
            "href": {
              "type": "string",
              "format": "uri",
              "pattern": "^https?://\\w+",
              "description": "URL for this link"
            },
            "template": {
              "type": "boolean",
              "description": "Is the HREF a RFC-6570 compliant URI Template"
            }
          },
          "required": [
            "href",
            "template"
          ]
        },
        "first": {
          "type": "object",
          "additionalProperties": false,
          "description": "Links to the first page of results for this resource",
          "properties": {
            "href": {
              "type": "string",
              "format": "uri",
              "pattern": "^https?://\\w+",
              "description": "URL for this link"
            },
            "template": {
              "type": "boolean",
              "description": "Is the HREF a RFC-6570 compliant URI Template"
            }
          },
          "required": [
            "href",
            "template"
          ]
        },
        "previous": {
          "type": "object",
          "additionalProperties": false,
          "description": "Links to the previous page of results for this resource",
          "properties": {
            "href": {
              "type": "string",
              "format": "uri",
              "pattern": "^https?://\\w+",
              "description": "URL for this link"
            },
            "template": {
              "type": "boolean",
              "description": "Is the HREF a RFC-6570 compliant URI Template"
            }
          },
          "required": [
            "href",
            "template"
          ]
        },
        "next": {
          "type": "object",
          "additionalProperties": false,
          "description": "Links to the next page of results for this resource",
          "properties": {
            "href": {
              "type": "string",
              "format": "uri",
              "pattern": "^https?://\\w+",
              "description": "URL for this link"
            },
            "template": {
              "type": "boolean",
              "description": "Is the HREF a RFC-6570 compliant URI Template"
            }
          },
          "required": [
            "href",
            "template"
          ]
        },
        "last": {
          "type": "object",
          "additionalProperties": false,
          "description": "Links to the last page of results for this resource",
          "properties": {
            "href": {
              "type": "string",
              "format": "uri",
              "pattern": "^https?://\\w+",
              "description": "URL for this link"
            },
            "template": {
              "type": "boolean",
              "description": "Is the HREF a RFC-6570 compliant URI Template"
            }
          },
          "required": [
            "href",
            "template"
          ]
        }
      },
      "required": [
        "self",
        "first"
      ]
    },
    "page": {
      "type": "integer",
      "description": "The page number"
    },
    "pageSize": {
      "type": "integer",
      "description": "The page size",
      "minimum": 10,
      "maximum": 100
    },
    "total": {
      "type": "integer",
      "description": "The total number of elements"
    },
    "clients": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "_links": {
            "type": "object",
            "additionalProperties": false,
            "description": "HATEOAS links",
            "properties": {
              "propertyLinks": {
                "type": "object",
                "additionalProperties": false,
                "description": "Link to the first page of this client's property links",
                "properties": {
                  "href": {
                    "type": "string",
                    "format": "uri",
                    "pattern": "^https?://\\w+",
                    "description": "URL for this link"
                  },
                  "template": {
                    "type": "boolean",
                    "description": "Is the HREF a RFC-6570 compliant URI Template"
                  }
                },
                "required": [
                  "href",
                  "template"
                ]
              }
            }
          },
          "organisationId": {
            "type": "integer",
            "description": "Unique ID for the client organisation"
          },
          "organisationName": {
            "type": "string",
            "description": "The name of the client organisation"
          },
          "appointedDate": {
            "type": "string",
            "format": "date",
            "description": "The date on which the agent was appointed to the property link"
          },
          "propertyCount": {
            "type": "integer",
            "description": "Number of properties managed for this client"
          }
        },
        "required": [
          "_links",
          "organisationId",
          "organisationName",
          "appointedDate",
          "propertyCount"
        ]
      }
    }
  },
  "required": [
    "_links",
    "page",
    "pageSize",
    "total",
    "clients"
  ]
}

=== AdamCoops/api-documentation-frontend/test/resources/raml/V2/business-rates/2.0/endpoints/my-organisation/clients/examples/get-my-clients-response-example.json
{
  "_links": {
    "self": {
      "href": "http://api.service.hmrc.gov.uk/my-organisation/clients?clientOrganisation=egg&page=1&pageSize=15",
      "template": false
    },
    "first": {
      "href": "http://api.service.hmrc.gov.uk/my-organisation/clients?clientOrganisation=egg&page=1&pageSize=15",
      "template": false
    },
    "last": {
      "href": "http://api.service.hmrc.gov.uk/my-organisation/clients?clientOrganisation=egg&page=1&pageSize=15",
      "template": false
    }
  },
  "page": 1,
  "pageSize": 15,
  "total": 2,
  "clients": [
    {
      "_links": {
        "propertyLinks": {
          "href": "http://api.service.hmrc.gov.uk/my-organisation/clients/all/property-links?clientOrganisation=Client%20Organisation%201&page=1&pageSize=15",
          "template": false
        }
      },
      "organisationId": 606,
      "organisationName": "Client Organisation 1",
      "appointedDate": "2020-03-24",
      "propertyCount": 2
    },
    {
      "_links": {
        "propertyLinks": {
          "href": "http://api.service.hmrc.gov.uk/my-organisation/clients/all/property-links?clientOrganisation=Another%20client&page=1&pageSize=15",
          "template": false
        }
      },
      "organisationId": 164,
      "organisationName": "Another client",
      "appointedDate": "2020-03-24",
      "propertyCount": 17
    }
  ]
}
